sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_script:
  - docker-compose up --build -d

script:
  - python testfile.py

after_script:
  - docker-compose down


notifications:
  email: 
    - vishvajit.pathak@gmail.com
